server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
          #file: ./config

  profiles:
    active: native

#eureka:
#  instance:
#    hostname: annuaire
#    port: 1111
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
##    serviceUrl:
##      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
##      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
